BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS users(
  email TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  company_name TEXT NOT NULL,
  password TEXT NOT NULL,
  phone TEXT NOT NULL,
  country_code TEXT NOT NULL,
  service_type TEXT NOT NULL,
  images JSON NOT NULL,
  training_files JSON NOT NULL,
  prompt TEXT NOT NULL,
  assistant_name TEXT,
  address TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions(
  email TEXT PRIMARY KEY,
  token TEXT NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(email) REFERENCES users(email) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS instances(
  email TEXT PRIMARY KEY,
  ip_address TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(email) REFERENCES users(email) ON DELETE CASCADE
);
COMMIT; 