BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS franchises(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  person_or_company_name TEXT NOT NULL,
  state_id TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  contracted_instances INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
COMMIT; 